[package]
edition = "2021"
name = "rebox-types"
version = "0.0.1"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
